In [2]:
using PythonCall

pd = pyimport("pandas")
plt = pyimport("matplotlib.pyplot")
ticker = pyimport("matplotlib.ticker")

df = pd.read_csv("C:\\Users\\Thinkpad\\dataset\\tweets.csv", index_col=nothing, encoding="ISO-8859-1")

df



,Target,ID,Date,flag,User,Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew
...,...,...,...,...,...,...
1048570,4,1960186342,Fri May 29 07:33:44 PDT 2009,NO_QUERY,Madelinedugganx,My GrandMa is making Dinenr with my Mum
1048571,4,1960186409,Fri May 29 07:33:43 PDT 2009,NO_QUERY,OffRoad_Dude,Mid-morning snack time... A bowl of cheese noo...
1048572,4,1960186429,Fri May 29 07:33:44 PDT 2009,NO_QUERY,Falchion,@ShaDeLa same here say it like from the Termi...
1048573,4,1960186445,Fri May 29 07:33:44 PDT 2009,NO_QUERY,jonasobsessedx,@DestinyHope92 im great thaanks wbuu?


In [3]:
grouped = df.groupby("Target")
#.apply(x -> x.sample(n=200, random_state=42))
df_sample = pd.concat([group.sample(n=200, random_state=42) for (name, group) in grouped])
df_sample.reset_index()

,index,Target,ID,Date,flag,User,Text
0,212188,0,1974671472,Sat May 30 13:36:33 PDT 2009,NO_QUERY,crail00,@dickiemaxx Win a few; lose few a with a
1,299036,0,1997882402,Mon Jun 01 17:37:12 PDT 2009,NO_QUERY,ana_leal,@lavjonas tokio hotel and won tokio hotel that...
2,475977,0,2177756662,Mon Jun 15 06:39:05 PDT 2009,NO_QUERY,x__claireyy__x,"Right, off to work Only 5 hours to go until I..."
3,385829,0,2053681109,Sat Jun 06 05:22:18 PDT 2009,NO_QUERY,karl_goddard,@daibarnes and guess who's landed that plum jo...
4,138859,0,1880667015,Fri May 22 02:03:41 PDT 2009,NO_QUERY,jocxie,@rabbit_rabid can't sleep... come give me hug...
...,...,...,...,...,...,...,...
395,982156,4,1834176189,Mon May 18 01:55:25 PDT 2009,NO_QUERY,tongits,"@joolzgirl haha! I understand, you can try it ..."
396,943638,4,1795178016,Thu May 14 07:18:12 PDT 2009,NO_QUERY,K2daLA,Doing Work As Always
397,852098,4,1572888403,Mon Apr 20 22:55:10 PDT 2009,NO_QUERY,J0SMILES,SO DON'T DO IT
398,993849,4,1835457156,Mon May 18 06:02:06 PDT 2009,NO_QUERY,tayyy625,schooool; last full weekkk! and then amandas ...


In [4]:
df_sample["Date"] = pd.to_datetime(df_sample["Date"], format = "%a %b %d %H:%M:%S PDT %Y")
df_sample["Month"] = df_sample["Date"].dt.month
ax = df_sample["Month"].value_counts().sort_index().plot(
    kind="bar", 
    title = "comments per month", 
    color = "blue", 
    figsize = (10, 5))
ax.set_xlabel("Months")
#plt.show()


Python: Text(0.5, 0, 'Months')

In [5]:
most_frequens_perMonth = df_sample.groupby("Target")["Month"].value_counts().unstack(fill_value = 0)
minor_locator = ticker.AutoMinorLocator(10)
ax = plt.figure(figsize=(10, 5)).add_subplot(111)
most_frequens_perMonth.plot(
    kind="bar",
    title = "comments per month", 
    xlabel = "Target",
    ylabel = "Number of comments",
    legend = true,
    
).grid(
    linestyle = "--",
    color = "grey",
    axis = "both",
    which = "both"
)
ax.yaxis.set_minor_locator(minor_locator)
plt.xticks(rotation = 0)
#plt.show()

Python: (array([0, 1]), [Text(0, 0, '0'), Text(1, 0, '4')])

In [6]:
most_frequens_perMonth

Month,4,5,6
Target,,,
0,11,49,140
4,47,153,0


In [7]:

df_sample["Text"] = map(x -> strip(lowercase(replace(string(x), r"(@\w+|\d+|[^\w\s])"=> ""))), df_sample["Text"])
df_filtered = df_sample.filter(["Target", "Text"], axis=1)


,Target,Text
212188,0,win a few lose few a with a
299036,0,tokio hotel and won tokio hotel thats bad
475977,0,right off to work only hours to go until im ...
385829,0,and guess whos landed that plum job moi were ...
138859,0,cant sleep come give me hug
...,...,...
982156,4,haha i understand you can try it anytime you w...
943638,4,doing work as always
852098,4,so dont do it
993849,4,schooool last full weekkk and then amandas to...


In [8]:
nltk = pyimport("nltk")

nltk.download("stopwords")
nltk.download("punkt")
nltk.download("wordnet")


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Thinkpad\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Thinkpad\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Thinkpad\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Python: True

In [9]:
stopwords = nltk.corpus.stopwords.words("english")
lemmatize = nltk.stem.WordNetLemmatizer()


function word_proccess(text) 

    tokens = nltk.word_tokenize(text)
    filtered_tokens = [lemmatize.lemmatize(token) for token in tokens if !(token in stopwords)]
    return filtered_tokens
    
end

df_filtered["Tokens"] = map(word_proccess, df_sample.Text)
df_filtered


,Target,Text,Tokens
212188,0,win a few lose few a with a,"[win, lose]"
299036,0,tokio hotel and won tokio hotel thats bad,"[tokio, hotel, tokio, hotel, thats, bad]"
475977,0,right off to work only hours to go until im ...,"[right, work, hour, go, im, free, xd]"
385829,0,and guess whos landed that plum job moi were ...,"[guess, who, landed, plum, job, moi, hosting, ..."
138859,0,cant sleep come give me hug,"[cant, sleep, come, give, hug]"
...,...,...,...
982156,4,haha i understand you can try it anytime you w...,"[haha, understand, try, anytime, want, looking..."
943638,4,doing work as always,"[work, always]"
852098,4,so dont do it,[dont]
993849,4,schooool last full weekkk and then amandas to...,"[schooool, last, full, weekkk, amandas, study,..."


In [10]:
sklearn = pyimport("sklearn")
gensim = pyimport("gensim")
np = pyimport("numpy")


Python: <module 'numpy' from 'C:\\Users\\Thinkpad\\.julia\\environments\\v1.11\\.CondaPkg\\env\\Lib\\site-packages\\numpy\\__init__.py'>

In [ ]:
model = gensim.models.Word2Vec(sentences = df_filtered["Tokens"], vector_size=100, window= 5, min_count=1, workers=4)

function text_to_vector(tokens, model)
    vectors = [np.copy(model.wv[token]) for token in tokens if haskey(model.wv, token)]
    return return length(vectors) > 0 ? np.mean(vectors, axis=0) : np.zeros(model.vector_size)
end

sentence_vectors = [text_to_vector(tokens, model) for tokens in df_filtered["Tokens"]]
sentence_vectors_df = np.array(sentence_vectors)
df_filtered["sentence_vector"] = sentence_vectors_df

vector = np.array(df_filtered["sentence_vector"].tolist()).copy()
y = np.array(df_filtered["Target"]).copy()

train_test_split = sklearn.model_selection.train_test_split

X_train, X_test, y_train, y_test = train_test_split(vector, y, test_size=0.4, random_state=42)

In [24]:
svm = sklearn.svm.SVC()
GridSearchCV = sklearn.model_selection.GridSearchCV

param = Dict(
    "C" => [0.1, 1, 10],
    "kernel" => ["linear", "rbf"],
    "gamma" => ["scale", "auto"]
)

params = PythonCall.pydict(param)

gridsearch = GridSearchCV(svm, params, cv=5, scoring="accuracy", error_score = "raise")
gridsearch.fit(X_train, y_train)

Python:
GridSearchCV(cv=5, error_score='raise', estimator=SVC(),
             param_grid={'C': Julia:
3-element Vector{Float64}:
  0.1
  1.0
 10.0,
                         'gamma': Julia:
2-element Vector{String}:
 "scale"
 "auto",
                         'kernel': Julia:
2-element Vector{String}:
 "linear"
 "rbf"},
             scoring='accuracy')

In [25]:
println("Best parameters: ", gridsearch.best_params_)
println("Best score: ", gridsearch.best_score_)
y_pred = gridsearch.predict(X_test)
accuracy = sklearn.metrics.accuracy_score(y_test, y_pred)

results = pd.DataFrame(gridsearch.cv_results_)
display(results)


,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001629,0.000816,0.000799,0.000746,0.1,scale,linear,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}",0.500000,0.515625,0.515625,0.515625,0.515625,0.512500,0.006250,3
1,0.000000,0.000000,0.002834,0.005669,0.1,scale,rbf,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'rbf'}",0.500000,0.515625,0.515625,0.515625,0.515625,0.512500,0.006250,3
2,0.004358,0.005735,0.001001,0.000002,0.1,auto,linear,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'linear'}",0.500000,0.515625,0.515625,0.515625,0.515625,0.512500,0.006250,3
3,0.003632,0.003196,0.000848,0.001042,0.1,auto,rbf,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'rbf'}",0.500000,0.515625,0.515625,0.515625,0.515625,0.512500,0.006250,3
4,0.003197,0.004671,0.000000,0.000000,1.0,scale,linear,"{'C': 1.0, 'gamma': 'scale', 'kernel': 'linear'}",0.500000,0.515625,0.515625,0.515625,0.515625,0.512500,0.006250,3
5,0.003594,0.007189,0.000271,0.000541,1.0,scale,rbf,"{'C': 1.0, 'gamma': 'scale', 'kernel': 'rbf'}",0.671875,0.625000,0.531250,0.562500,0.531250,0.584375,0.055551,1
6,0.002813,0.003788,0.000000,0.000000,1.0,auto,linear,"{'C': 1.0, 'gamma': 'auto', 'kernel': 'linear'}",0.500000,0.515625,0.515625,0.515625,0.515625,0.512500,0.006250,3
7,0.001400,0.001200,0.004191,0.005928,1.0,auto,rbf,"{'C': 1.0, 'gamma': 'auto', 'kernel': 'rbf'}",0.500000,0.515625,0.515625,0.515625,0.515625,0.512500,0.006250,3
8,0.000800,0.000980,0.000419,0.000516,10.0,scale,linear,"{'C': 10.0, 'gamma': 'scale', 'kernel': 'linear'}",0.500000,0.515625,0.515625,0.515625,0.515625,0.512500,0.006250,3
9,0.002403,0.003206,0.004981,0.005087,10.0,scale,rbf,"{'C': 10.0, 'gamma': 'scale', 'kernel': 'rbf'}",0.609375,0.640625,0.500000,0.593750,0.468750,0.562500,0.066291,2


Best parameters: {'C': 1.0, 'gamma': 'scale', 'kernel': 'rbf'}
Best score: 0.584375
